name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install protobuf
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: make check test

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            rust-target: aarch64-apple-darwin
          - arch: x86_64
            rust-target: x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install protobuf
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-target }}
      - run: make build CONFIGURATION=Release ARCH=${{ matrix.arch }}
